name: Build and run container

on:
  # push:
  workflow_dispatch:

jobs:
  job1:
    name: BuildAndRun
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & tag image
        id: build-image
        run: |
          # Build a docker container
          docker build -f ./Dockerfile -t expose_me:latest .

      - name: Start container
        id: start-container
        run: |
          # Start container and make it available
          docker run -i expose_me:latest
